# Generated by Django 6.0.6 on 2026-06-06 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('normalized_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('google_maps', 'Google Maps Scraper'), ('instagram', 'Instagram Scraper')], max_length=30)),
                ('status', models.CharField(choices=[('novo', 'Novo Lead'), ('contatado', 'Contatado'), ('negociacao', 'Em Negociação'), ('retornou', 'Retornou'), ('fechado', 'Fechado (Ganho)'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('quality_score', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('action_type', models.CharField(choices=[('creation', 'Criação'), ('edit', 'Edição'), ('status_change', 'Alteração de Status'), ('note', 'Observação Interna')], default='note', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', 'normalized_phone'], name='leads_lead_user_id_dd58f7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', 'name'], name='leads_lead_user_id_0730dd_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'),
        ),
    ]
