# Generated by Django 6.0.6 on 2026-06-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='maps_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link Google Maps'),
        ),
        migrations.AddField(
            model_name='lead',
            name='twitter',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='youtube',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
