# Generated by Django 6.0.6 on 2026-06-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_maps_url_lead_twitter_lead_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='business_hours',
            field=models.JSONField(blank=True, help_text='Dict com dias da semana e horários', null=True, verbose_name='Horários de funcionamento (JSON)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='maps_share_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link curto Google (share.google)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='recent_reviews',
            field=models.JSONField(blank=True, help_text='Lista das últimas 10 avaliações do Google Maps', null=True, verbose_name='Avaliações recentes (JSON)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='website_detected_type',
            field=models.CharField(blank=True, choices=[('website', 'Site próprio'), ('instagram', 'Link Instagram'), ('whatsapp', 'Link WhatsApp'), ('facebook', 'Link Facebook'), ('youtube', 'Link YouTube'), ('linktree', 'Linktree / Bio link'), ('other_social', 'Outra rede social')], max_length=20, null=True, verbose_name='Tipo real do link de site'),
        ),
    ]
