# Generated by Django 6.0.6 on 2026-06-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_business_hours_lead_maps_share_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
