# Generated by Django 6.0.6 on 2026-06-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='amenities',
            field=models.JSONField(blank=True, help_text='Lista de atributos do lugar: Wi-Fi, estacionamento, acessibilidade etc.', null=True, verbose_name='Amenidades / Atributos'),
        ),
        migrations.AddField(
            model_name='lead',
            name='plus_code',
            field=models.CharField(blank=True, help_text='Ex: 5HMG+V3 Ribeirão Preto', max_length=20, null=True, verbose_name='Plus Code'),
        ),
        migrations.AddField(
            model_name='lead',
            name='price_range',
            field=models.CharField(blank=True, help_text='Ex: $, $$, $$$, $$$$', max_length=10, null=True, verbose_name='Faixa de preço ($, $$, $$$)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='total_photos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de fotos no Maps'),
        ),
    ]
