# Generated by Django 6.0.6 on 2026-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_amenities_lead_plus_code_lead_price_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='score_breakdown',
            field=models.JSONField(blank=True, null=True, verbose_name='Detalhamento da pontuação'),
        ),
    ]
