# Generated by Django 6.0.6 on 2026-06-15 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_generatedcontract_client_name_generatedcontract_lead_and_more'),
        ('leads', '0006_lead_score_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_leads', to='contracts.generatedcontract'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='final_site_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='preview_site_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='project_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo Lead'), ('contatado', 'Contatado'), ('negociacao', 'Em Negociação'), ('retornou', 'Retornou'), ('fechado', 'Em Produção'), ('finalizado', 'Projeto Entregue'), ('perdido', 'Perdido')], default='novo', max_length=20),
        ),
    ]
