# Generated by Django 6.0.6 on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_remove_retornou_status'),
    ]

    # A data migration lead_scoring.0003_recalculate_leads itera o modelo Lead
    # "vivo" (com email). Em bancos novos, o email precisa existir antes dela.
    run_before = [
        ('lead_scoring', '0003_recalculate_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
