# Generated by Django 6.0.6 on 2026-06-15 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0004_generatedcontract_client_name_generatedcontract_lead_and_more'),
        ('leads', '0007_lead_contract_lead_contract_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('income', 'Entrada'), ('expense', 'Despesa')], max_length=10)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(default='fa-circle', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Finance categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('income', 'Entrada'), ('expense', 'Despesa')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=12)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='finance_attachments/')),
                ('attachment_kind', models.CharField(choices=[('none', 'Nenhum'), ('receipt', 'Comprovante'), ('statement', 'Extrato')], default='none', max_length=12)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('contract_auto', 'Contrato automático'), ('status_trigger', 'Gatilho de status'), ('recurring', 'Recorrente')], default='manual', max_length=20)),
                ('payment_plan_key', models.CharField(blank=True, default='', help_text='Chave idempotente do plano (ex: metade_2, parcela_3)', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.financecategory')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to='contracts.generatedcontract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to='leads.lead')),
                ('parent_recurring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='finance.financeentry')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['entry_type', 'date'], name='finance_fin_entry_t_43cddc_idx'), models.Index(fields=['status', 'due_date'], name='finance_fin_status_889d5d_idx')],
            },
        ),
    ]
