# Generated by Django 5.2.13 on 2026-06-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='field_schema',
            field=models.JSONField(blank=True, default=list, help_text='Form field definitions for the template'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='structure',
            field=models.JSONField(blank=True, default=dict, help_text='Segmented blocks: static vs variable'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generatedcontract',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
