# Generated by Django 6.0.6 on 2026-06-15 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contracttemplate_id_alter_generatedcontract_id'),
        ('leads', '0006_lead_score_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontract',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='generatedcontract',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='generatedcontract',
            name='payment_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
