# Generated by Django 6.0.6 on 2026-06-12 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('points', models.IntegerField(help_text='Pontos somados (ou subtraídos se negativo) quando a regra bater.')),
                ('priority', models.IntegerField(default=0, help_text='Ordem de exibição no breakdown (maior primeiro).')),
                ('is_active', models.BooleanField(default=True)),
                ('match_mode', models.CharField(choices=[('all', 'Todas as condições'), ('any', 'Qualquer condição')], default='all', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de pontuação',
                'verbose_name_plural': 'Regras de pontuação',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScoringCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(max_length=120)),
                ('operator', models.CharField(choices=[('exists', 'Existe / preenchido'), ('empty', 'Vazio / ausente'), ('eq', 'Igual a'), ('neq', 'Diferente de'), ('contains', 'Contém'), ('in', 'Está na lista'), ('not_in', 'Não está na lista'), ('gt', 'Maior que'), ('gte', 'Maior ou igual a'), ('lt', 'Menor que'), ('lte', 'Menor ou igual a'), ('between', 'Entre (min e max)'), ('is_true', 'É verdadeiro'), ('is_false', 'É falso'), ('json_count_gte', 'Quantidade JSON ≥'), ('json_count_lte', 'Quantidade JSON ≤')], max_length=20)),
                ('value', models.JSONField(blank=True, default=None, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='lead_scoring.scoringrule')),
            ],
            options={
                'verbose_name': 'Condição de pontuação',
                'verbose_name_plural': 'Condições de pontuação',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
