# Generated by Django 5.2.2 on 2026-06-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='face_login_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
