# Generated by Django 5.2.13 on 2026-06-16 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0008_alter_lead_id_alter_leadnote_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('core_web_vitals', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_audits', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
