# Generated by Django 6.0.6 on 2026-06-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0002_siteauditvisualasset'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='siteauditvisualasset',
            new_name='site_audit__expires_dc61e6_idx',
            old_name='site_audit__expires_6a8f2d_idx',
        ),
    ]
