# Generated by Django 5.2.13 on 2026-06-10 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Cadastro'), ('face_register', 'Cadastro facial'), ('lead_create', 'Lead criado'), ('lead_update', 'Lead atualizado'), ('lead_delete', 'Lead excluído'), ('lead_bulk_delete', 'Leads excluídos em massa'), ('lead_delete_all', 'Todos os leads excluídos'), ('lead_import', 'Importação de leads'), ('lead_export', 'Exportação de leads'), ('instagram_scrape', 'Extração Instagram'), ('contract_template_upload', 'Template de contrato enviado'), ('contract_template_delete', 'Template excluído'), ('contract_generate', 'Contrato gerado'), ('contract_download', 'Contrato baixado'), ('contract_delete', 'Contrato excluído')], max_length=50)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_activ_created_b8d8e7_idx'), models.Index(fields=['action'], name='audit_activ_action_259cfa_idx'), models.Index(fields=['user', '-created_at'], name='audit_activ_user_id_60d287_idx')],
            },
        ),
    ]
