# Generated by Django 6.0.6 on 2026-06-18 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0009_remove_retornou_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Comercial, Suporte', max_length=120, verbose_name='Nome amigável')),
                ('instance_name', models.CharField(help_text='Identificador da instância no Evolution API', max_length=120, unique=True, verbose_name='Instância (Evolution)')),
                ('phone_number', models.CharField(blank=True, default='', max_length=30, verbose_name='Número (somente dígitos)')),
                ('api_url', models.URLField(blank=True, default='', max_length=500)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('created', 'Criada'), ('connecting', 'Conectando (aguardando QR)'), ('connected', 'Conectada'), ('disconnected', 'Desconectada')], default='created', max_length=15)),
                ('is_default', models.BooleanField(default=False, verbose_name='Número padrão para envios')),
                ('is_active', models.BooleanField(default=True)),
                ('last_qr_base64', models.TextField(blank=True, default='')),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instância WhatsApp',
                'verbose_name_plural': 'Instâncias WhatsApp',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('out', 'Enviada'), ('in', 'Recebida')], max_length=3)),
                ('remote_jid', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('document', 'Documento'), ('sticker', 'Figurinha'), ('location', 'Localização'), ('contact', 'Contato'), ('other', 'Outro')], default='text', max_length=15)),
                ('text', models.TextField(blank=True, default='')),
                ('media_url', models.URLField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('received', 'Recebida'), ('failed', 'Falhou')], default='pending', max_length=12)),
                ('evolution_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('error', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappinstance')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['timestamp', 'created_at'],
                'indexes': [models.Index(fields=['user', 'phone'], name='whatsapp_wh_user_id_ebbbfe_idx'), models.Index(fields=['lead', 'created_at'], name='whatsapp_wh_lead_id_41ef96_idx')],
            },
        ),
    ]
